/**
 * AiRiskInsight
 * =============
 * Explainability panel for a single equipment risk assessment.
 *
 * Answers four operator questions using only data that already exists in
 * the GridWise risk engine output — no text is invented.
 *
 *   1. What is happening?      ← sensor readings + risk score (DATA)
 *   2. Why is it happening?    ← contributing_factors[] from engine (CALCULATION)
 *   3. What could happen?      ← outage_probability + customers_affected (CALCULATION)
 *   4. What should I do?       ← recommended_actions[] or Recommendation[] (ENGINE OUTPUT)
 *
 * Source provenance is labelled on every section so operators know
 * exactly what they are reading.
 */

import { useState } from "react";
import {
  Cpu, AlertTriangle, TrendingUp, ShieldCheck, ChevronDown, ChevronUp,
  Database, Calculator, Sparkles, Info, Clock,
} from "lucide-react";
import { cn } from "@/lib/cn";
import { RiskBadge } from "@/components/common/RiskBadge";
import { formatNumber, formatRelativeTime } from "@/lib/formatters";
import type { RiskScore, RiskFactor } from "@/types/risk";
import type { EquipmentDetail, EquipmentReading } from "@/types/equipment";
import type { Recommendation } from "@/types/recommendation";

// ─────────────────────────────────────────────────────────────────────────────
// Prop types
// ─────────────────────────────────────────────────────────────────────────────

export interface AiRiskInsightProps {
  /** Full equipment asset record */
  detail: EquipmentDetail;
  /** Stored risk score (from /equipment/{id}/risk) */
  riskScore: RiskScore;
  /** Recommendations from /equipment/{id}/recommendations */
  recommendations: Recommendation[];
  /**
   * contributing_factors[] and recommended_actions[] from the risk engine
   * (available on the extended RiskScore response as optional fields — the
   * simulator endpoint returns them; the stored score endpoint may not).
   * If absent the component falls back gracefully.
   */
  contributingFactors?: string[];
  engineActions?: string[];
}

// ─────────────────────────────────────────────────────────────────────────────
// Provenance badge — makes data source explicit on every section
// ─────────────────────────────────────────────────────────────────────────────

type Provenance = "data" | "calculation" | "engine";

const PROVENANCE_META: Record<Provenance, {
  icon:  React.ElementType;
  label: string;
  title: string;
  color: string;
  border: string;
  bg:    string;
}> = {
  data: {
    icon:   Database,
    label:  "Sensor data",
    title:  "Values read directly from equipment sensor snapshots — no inference applied.",
    color:  "text-[var(--color-brand)]",
    border: "border-[rgba(59,130,246,.25)]",
    bg:     "bg-[rgba(59,130,246,.06)]",
  },
  calculation: {
    icon:   Calculator,
    label:  "Risk calculation",
    title:  "Output of the GridWise weighted-factor scoring model. Heuristic estimate only.",
    color:  "text-[var(--color-medium-tx)]",
    border: "border-[rgba(234,179,8,.25)]",
    bg:     "bg-[rgba(234,179,8,.04)]",
  },
  engine: {
    icon:   Sparkles,
    label:  "Engine output",
    title:  "Generated by the GridWise Risk Engine explanation and recommendation modules. Not certified advice.",
    color:  "text-[var(--color-ai-purple)]",
    border: "border-[rgba(139,92,246,.25)]",
    bg:     "bg-[rgba(139,92,246,.05)]",
  },
};

function ProvenanceBadge({ type }: { type: Provenance }) {
  const m = PROVENANCE_META[type];
  return (
    <span
      title={m.title}
      className={cn(
        "inline-flex items-center gap-1 text-[9px] font-semibold uppercase tracking-wider",
        "rounded-full border px-1.5 py-0.5 cursor-help",
        m.color, m.border, m.bg,
      )}
    >
      <m.icon size={8} />
      {m.label}
    </span>
  );
}

// ─────────────────────────────────────────────────────────────────────────────
// Section wrapper — collapsible panel with provenance label
// ─────────────────────────────────────────────────────────────────────────────

function InsightSection({
  step,
  question,
  provenance,
  icon: Icon,
  accent,
  children,
  defaultOpen = true,
}: {
  step:        number;
  question:    string;
  provenance:  Provenance;
  icon:        React.ElementType;
  accent:      string;   // CSS colour value
  children:    React.ReactNode;
  defaultOpen?: boolean;
}) {
  const [open, setOpen] = useState(defaultOpen);

  return (
    <div className="rounded-lg border border-[var(--color-base-4)] overflow-hidden">
      <button
        type="button"
        onClick={() => setOpen((o) => !o)}
        className="w-full flex items-center gap-3 px-4 py-3 text-left bg-[var(--color-base-2)] hover:bg-[var(--color-base-3)] transition-colors"
        aria-expanded={open}
      >
        {/* Step number */}
        <span
          className="shrink-0 w-6 h-6 rounded-full flex items-center justify-center text-[10px] font-bold text-white"
          style={{ background: accent }}
        >
          {step}
        </span>

        {/* Icon + question */}
        <div className="flex items-center gap-2 flex-1 min-w-0">
          <Icon size={13} style={{ color: accent }} className="shrink-0" />
          <span className="text-[13px] font-semibold text-[var(--color-text-0)] truncate">
            {question}
          </span>
        </div>

        {/* Provenance + chevron */}
        <div className="flex items-center gap-2 shrink-0">
          <ProvenanceBadge type={provenance} />
          {open
            ? <ChevronUp size={14} className="text-[var(--color-text-3)]" />
            : <ChevronDown size={14} className="text-[var(--color-text-3)]" />}
        </div>
      </button>

      {open && (
        <div className="px-4 py-4 bg-[var(--color-base-1)] border-t border-[var(--color-base-4)]">
          {children}
        </div>
      )}
    </div>
  );
}

// ─────────────────────────────────────────────────────────────────────────────
// Reading pill — a single sensor value with optional threshold colouring
// ─────────────────────────────────────────────────────────────────────────────

function ReadingPill({
  label,
  value,
  unit = "",
  decimals = 1,
  warnAbove,
  critAbove,
}: {
  label:      string;
  value:      number | null | undefined;
  unit?:      string;
  decimals?:  number;
  warnAbove?: number;
  critAbove?: number;
}) {
  if (value == null) return null;
  const isCrit = critAbove != null && value >= critAbove;
  const isWarn = warnAbove != null && value >= warnAbove && !isCrit;
  const valueColor = isCrit
    ? "text-[var(--color-critical-tx)]"
    : isWarn
    ? "text-[var(--color-high-tx)]"
    : "text-[var(--color-text-0)]";

  return (
    <div className={cn(
      "flex flex-col gap-0.5 px-3 py-2 rounded border",
      isCrit ? "bg-[var(--color-critical-bg)] border-[var(--color-critical-bd)]"
             : isWarn ? "bg-[var(--color-high-bg)] border-[var(--color-high-bd)]"
             : "bg-[var(--color-base-3)] border-[var(--color-base-4)]"
    )}>
      <span className="text-[9px] font-semibold uppercase tracking-widest text-[var(--color-text-3)]">
        {label}
      </span>
      <span className={cn("font-mono text-[15px] font-bold leading-none", valueColor)}>
        {value.toFixed(decimals)}{unit}
      </span>
    </div>
  );
}

// ─────────────────────────────────────────────────────────────────────────────
// Inline factor chip — compact factor contribution display
// ─────────────────────────────────────────────────────────────────────────────

function FactorChip({ factor }: { factor: RiskFactor }) {
  const pct = Math.round(factor.normalized_value * 100);
  const color =
    pct >= 75 ? "var(--color-critical)" :
    pct >= 50 ? "var(--color-high)" :
    pct >= 25 ? "var(--color-medium)" :
    "var(--color-low)";

  return (
    <div className="flex items-center gap-2">
      {factor.is_primary_driver && (
        <span className="text-[9px] font-bold text-[var(--color-brand)] border border-[rgba(59,130,246,.35)] rounded px-1 py-0.5 uppercase tracking-wider shrink-0">
          Primary
        </span>
      )}
      <span className="text-[12px] text-[var(--color-text-1)] min-w-0 truncate">{factor.label}</span>
      <div className="flex-1 h-1.5 rounded-full bg-[var(--color-base-4)] overflow-hidden min-w-[40px]">
        <div
          className="h-full rounded-full"
          style={{ width: `${pct}%`, background: color }}
          title={`Normalised: ${pct}%`}
        />
      </div>
      <span className="font-mono text-[10px] text-[var(--color-text-3)] shrink-0 w-8 text-right">
        {factor.weighted_contribution.toFixed(1)}%
      </span>
    </div>
  );
}

// ─────────────────────────────────────────────────────────────────────────────
// Outage impact gauge
// ─────────────────────────────────────────────────────────────────────────────

function OutageGauge({ probability, customers }: { probability: number; customers: number }) {
  const pct = probability * 100;
  const color =
    pct >= 60 ? "var(--color-critical)" :
    pct >= 35 ? "var(--color-high)" :
    pct >= 15 ? "var(--color-medium)" :
    "var(--color-low)";

  return (
    <div className="space-y-3">
      <div className="space-y-1.5">
        <div className="flex items-center justify-between text-[11px]">
          <span className="text-[var(--color-text-3)] font-medium">
            Outage probability (independent-failure model)
          </span>
          <span className="font-mono font-bold text-[13px]" style={{ color }}>
            {pct.toFixed(1)}%
          </span>
        </div>
        <div className="h-2.5 rounded-full bg-[var(--color-base-4)] overflow-hidden">
          <div
            className="h-full rounded-full transition-all"
            style={{ width: `${Math.min(pct, 100)}%`, background: color }}
          />
        </div>
        <div className="flex justify-between text-[9px] text-[var(--color-text-3)]">
          <span>0% — Negligible</span>
          <span>35% — Medium</span>
          <span>60% — High</span>
          <span>100%</span>
        </div>
      </div>

      <div className="flex items-center gap-3 p-3 rounded-lg border border-[var(--color-base-4)] bg-[var(--color-base-3)]">
        <div>
          <p className="text-[10px] font-semibold uppercase tracking-widest text-[var(--color-text-3)]">
            Estimated customers at risk
          </p>
          <p className="font-mono text-[20px] font-bold text-[var(--color-text-0)] leading-tight">
            {formatNumber(customers)}
          </p>
          <p className="text-[10px] text-[var(--color-text-3)] italic mt-0.5">
            Expected-value estimate: P(outage) × customers served
          </p>
        </div>
      </div>
    </div>
  );
}

// ─────────────────────────────────────────────────────────────────────────────
// Action row
// ─────────────────────────────────────────────────────────────────────────────

function ActionRow({
  index,
  text,
  priority,
}: {
  index: number;
  text: string;
  priority?: "urgent" | "scheduled" | "monitor";
}) {
  const pillStyle = {
    urgent:    "bg-[var(--color-critical-bg)] border-[var(--color-critical-bd)] text-[var(--color-critical-tx)]",
    scheduled: "bg-[var(--color-high-bg)] border-[var(--color-high-bd)] text-[var(--color-high-tx)]",
    monitor:   "bg-[var(--color-base-3)] border-[var(--color-base-4)] text-[var(--color-text-2)]",
  };
  const numColor = {
    urgent:    "text-[var(--color-critical-tx)]",
    scheduled: "text-[var(--color-high-tx)]",
    monitor:   "text-[var(--color-text-3)]",
  };
  const p = priority ?? "monitor";

  return (
    <div className="flex items-start gap-3">
      <span className={cn("shrink-0 font-mono text-[13px] font-bold leading-none mt-0.5 select-none w-5 text-right", numColor[p])}>
        {index + 1}.
      </span>
      <div className="space-y-1 min-w-0">
        {priority && (
          <span className={cn("text-[9px] font-bold uppercase tracking-wider rounded border px-1.5 py-0.5", pillStyle[p])}>
            {priority}
          </span>
        )}
        <p className="text-[12px] leading-snug text-[var(--color-text-1)]">{text}</p>
      </div>
    </div>
  );
}

// ─────────────────────────────────────────────────────────────────────────────
// Section 1 helper — build "what is happening" narrative from data
// ─────────────────────────────────────────────────────────────────────────────

function buildStatusLine(
  detail: EquipmentDetail,
  riskScore: RiskScore,
  reading: EquipmentReading | undefined,
): string {
  const parts: string[] = [];
  parts.push(`${detail.name} (${detail.type}) is scoring ${riskScore.score.toFixed(0)}/100 risk`);
  parts.push(`— ${riskScore.level.toUpperCase()} level`);
  if (reading) {
    if (reading.load_pct >= 85) parts.push(`with load at ${reading.load_pct.toFixed(0)}% (high)`);
    else if (reading.temperature_c >= 75) parts.push(`with temperature at ${reading.temperature_c.toFixed(0)}°C (elevated)`);
  }
  if (detail.maintenance_days_ago > 180) {
    parts.push(`and ${detail.maintenance_days_ago}d since last maintenance`);
  }
  parts.push(".");
  return parts.join(" ");
}

// ─────────────────────────────────────────────────────────────────────────────
// Main component
// ─────────────────────────────────────────────────────────────────────────────

export function AiRiskInsight({
  detail,
  riskScore,
  recommendations,
  contributingFactors = [],
  engineActions = [],
}: AiRiskInsightProps) {
  const reading = detail.current_reading;
  const level   = riskScore.level;

  const levelAccent: Record<string, string> = {
    critical: "var(--color-critical)",
    high:     "var(--color-high)",
    medium:   "var(--color-medium)",
    low:      "var(--color-low)",
    unknown:  "var(--color-text-3)",
  };
  const accent = levelAccent[level] ?? levelAccent.unknown;

  // Sort factors by contribution for "Why" section
  const sortedFactors = [...riskScore.factors].sort(
    (a, b) => b.weighted_contribution - a.weighted_contribution,
  );

  // Merge action sources: Recommendation[] takes priority (has rationale),
  // engineActions[] fills in if recommendations are absent
  const hasStoredRecs  = recommendations.length > 0;
  const hasEngineActs  = engineActions.length > 0;

  // Status summary line (data-grounded, no invention)
  const statusLine = buildStatusLine(detail, riskScore, reading);

  return (
    <div className="space-y-2">

      {/* ── Header ── */}
      <div className="flex items-center gap-2 px-1">
        <Sparkles size={13} className="text-[var(--color-ai-purple)]" />
        <h3 className="text-[14px] font-semibold text-[var(--color-text-0)]">
          AI Risk Insight
        </h3>
        <RiskBadge level={level} size="sm" />
        {riskScore.scored_at && (
          <span className="ml-auto flex items-center gap-1 text-[10px] text-[var(--color-text-3)]">
            <Clock size={10} />
            {formatRelativeTime(String(riskScore.scored_at))}
          </span>
        )}
      </div>

      {/* ── Methodology notice ── */}
      <div className="flex items-start gap-2 px-3 py-2.5 rounded-lg border border-[rgba(139,92,246,.2)] bg-[rgba(139,92,246,.04)] text-[10px] text-[var(--color-text-3)]">
        <Info size={11} className="text-[var(--color-ai-purple)] shrink-0 mt-0.5" />
        <p>
          Insights are derived from the GridWise weighted-factor scoring engine.
          They are <span className="font-semibold text-[var(--color-text-2)]">heuristic estimates</span>, not certified engineering assessments.
          Provenance is labelled on each section —
          <span className="text-[var(--color-brand)] font-semibold"> Sensor data</span> ·
          <span className="text-[var(--color-medium-tx)] font-semibold"> Risk calculation</span> ·
          <span className="text-[var(--color-ai-purple)] font-semibold"> Engine output</span>.
        </p>
      </div>

      {/* ══════════════════════════════════════════════════════════════════
          SECTION 1 — What is happening?
      ══════════════════════════════════════════════════════════════════ */}
      <InsightSection
        step={1}
        question="What is happening?"
        provenance="data"
        icon={Cpu}
        accent="var(--color-brand)"
        defaultOpen
      >
        <div className="space-y-3">
          {/* Status sentence */}
          <p className="text-[13px] text-[var(--color-text-1)] leading-snug">
            {statusLine}
          </p>

          {/* Current readings grid */}
          {reading && (
            <div className="grid grid-cols-3 sm:grid-cols-4 gap-2">
              <ReadingPill label="Load"        value={reading.load_pct}           unit="%" decimals={0} warnAbove={80} critAbove={90} />
              <ReadingPill label="Temperature" value={reading.temperature_c}      unit="°C" decimals={0} warnAbove={75} critAbove={90} />
              <ReadingPill label="Vibration"   value={reading.vibration_mms}      unit=" mm/s" decimals={1} warnAbove={4} critAbove={7} />
              <ReadingPill label="Volt. Dev."  value={reading.voltage_deviation_pct} unit="%" decimals={1} warnAbove={10} critAbove={20} />
            </div>
          )}

          {/* Asset context */}
          <div className="flex flex-wrap gap-x-4 gap-y-1 text-[11px] text-[var(--color-text-3)]">
            <span>Age: <span className="text-[var(--color-text-2)] font-medium">{detail.age_years} yrs</span></span>
            <span>Maintenance: <span className="text-[var(--color-text-2)] font-medium">{detail.maintenance_days_ago}d ago</span></span>
            <span>Failures (2yr): <span className="text-[var(--color-text-2)] font-medium">{detail.previous_failures_2yr}</span></span>
            {reading?.weather_condition && reading.weather_condition !== "normal" && (
              <span>Weather: <span className="text-[var(--color-high-tx)] font-medium capitalize">{reading.weather_condition.replace("_", " ")}</span></span>
            )}
          </div>

          <p className="text-[10px] text-[var(--color-text-3)] italic">
            Source: latest sensor snapshot for {detail.id} · risk score {riskScore.score.toFixed(1)}/100
          </p>
        </div>
      </InsightSection>

      {/* ══════════════════════════════════════════════════════════════════
          SECTION 2 — Why is it happening?
      ══════════════════════════════════════════════════════════════════ */}
      <InsightSection
        step={2}
        question="Why is it happening?"
        provenance="calculation"
        icon={AlertTriangle}
        accent="var(--color-medium)"
        defaultOpen
      >
        <div className="space-y-3">
          {/* Engine contributing factor sentences */}
          {contributingFactors.length > 0 ? (
            <div className="space-y-1.5">
              {contributingFactors.map((sentence, i) => (
                <div
                  key={i}
                  className={cn(
                    "flex gap-2.5 px-3 py-2.5 rounded-lg border text-[12px] leading-snug",
                    i === 0
                      ? "bg-[var(--color-critical-bg)] border-[var(--color-critical-bd)] text-[var(--color-critical-tx)]"
                      : "bg-[var(--color-base-3)] border-[var(--color-base-4)] text-[var(--color-text-1)]",
                  )}
                >
                  <span
                    className={cn(
                      "shrink-0 w-4 h-4 rounded-full flex items-center justify-center text-[9px] font-bold mt-0.5",
                      i === 0
                        ? "bg-[var(--color-critical)] text-white"
                        : "bg-[var(--color-base-5)] text-[var(--color-text-2)]",
                    )}
                  >
                    {i + 1}
                  </span>
                  {sentence}
                </div>
              ))}
            </div>
          ) : null}

          {/* Factor bars — always shown (they are the calculation) */}
          {sortedFactors.length > 0 && (
            <div className="space-y-2 pt-1">
              <p className="text-[10px] font-semibold uppercase tracking-widest text-[var(--color-text-3)]">
                Scoring model — factor contributions
              </p>
              {sortedFactors.map((f) => (
                <FactorChip key={f.name} factor={f} />
              ))}
              <p className="text-[10px] text-[var(--color-text-3)] italic">
                Weighted-factor model: each row shows normalised value × weight → contribution % of total score.
              </p>
            </div>
          )}
        </div>
      </InsightSection>

      {/* ══════════════════════════════════════════════════════════════════
          SECTION 3 — What could happen?
      ══════════════════════════════════════════════════════════════════ */}
      <InsightSection
        step={3}
        question="What could happen?"
        provenance="calculation"
        icon={TrendingUp}
        accent={accent}
        defaultOpen
      >
        <div className="space-y-3">
          <OutageGauge
            probability={riskScore.outage_probability}
            customers={riskScore.estimated_customers_affected}
          />

          {/* Consequence sentence — grounded in data only */}
          <div
            className="px-3 py-2.5 rounded-lg border text-[12px] leading-snug"
            style={{
              background:   `var(--color-${level}-bg)`,
              borderColor:  `var(--color-${level}-bd)`,
              color:        `var(--color-${level}-tx)`,
            }}
          >
            {level === "critical" && (
              <>A {riskScore.score.toFixed(0)}/100 score places this equipment in the <strong>CRITICAL</strong> tier.
              At {(riskScore.outage_probability * 100).toFixed(0)}% outage probability,
              this unit poses the highest failure risk in the grid.
              Immediate intervention is required.</>
            )}
            {level === "high" && (
              <>At {riskScore.score.toFixed(0)}/100 (<strong>HIGH</strong>), there is a {(riskScore.outage_probability * 100).toFixed(0)}% estimated chance of a
              fault contributing to a zone outage. Urgent inspection is warranted.</>
            )}
            {level === "medium" && (
              <>Score {riskScore.score.toFixed(0)}/100 (<strong>MEDIUM</strong>) — {(riskScore.outage_probability * 100).toFixed(0)}% estimated outage contribution probability.
              Schedule maintenance before conditions worsen.</>
            )}
            {level === "low" && (
              <>Score {riskScore.score.toFixed(0)}/100 (<strong>LOW</strong>) — equipment is operating within acceptable parameters.
              Continue standard monitoring. No immediate risk is indicated.</>
            )}
            {(level === "unknown" || !["critical","high","medium","low"].includes(level)) && (
              <>Risk level is not yet determined for this equipment.</>
            )}
          </div>

          <p className="text-[10px] text-[var(--color-text-3)] italic">
            Outage probability derived from the independent-failure zone model.
            Customers-at-risk = P(outage) × {formatNumber(detail.customers_affected)} customers served.
            These are prototype estimates only.
          </p>
        </div>
      </InsightSection>

      {/* ══════════════════════════════════════════════════════════════════
          SECTION 4 — What should the operator do?
      ══════════════════════════════════════════════════════════════════ */}
      <InsightSection
        step={4}
        question="What should the operator do?"
        provenance="engine"
        icon={ShieldCheck}
        accent="var(--color-ai-purple)"
        defaultOpen
      >
        <div className="space-y-3">
          {/* No actions */}
          {!hasStoredRecs && !hasEngineActs && (
            <p className="text-[12px] text-[var(--color-text-3)] italic">
              No actions are currently recommended. Continue standard monitoring.
            </p>
          )}

          {/* Stored recommendations (have rationale, priority) — preferred source */}
          {hasStoredRecs && (
            <div className="space-y-2">
              <p className="text-[10px] font-semibold uppercase tracking-widest text-[var(--color-text-3)]">
                Stored recommendations
              </p>
              {recommendations.map((rec, i) => (
                <ActionRow
                  key={rec.id}
                  index={i}
                  text={rec.action}
                  priority={rec.priority}
                />
              ))}
              {recommendations[0]?.generated_at && (
                <p className="text-[10px] text-[var(--color-text-3)] italic">
                  Generated {formatRelativeTime(recommendations[0].generated_at)} · {recommendations.length} recommendation{recommendations.length !== 1 ? "s" : ""}
                </p>
              )}
            </div>
          )}

          {/* Engine actions — shown when no stored recs, or as supplemental */}
          {!hasStoredRecs && hasEngineActs && (
            <div className="space-y-2">
              <p className="text-[10px] font-semibold uppercase tracking-widest text-[var(--color-text-3)]">
                Engine-generated actions
              </p>
              {engineActions.map((action, i) => (
                <ActionRow key={i} index={i} text={action} />
              ))}
            </div>
          )}

          {/* Disclaimer */}
          <p className="text-[10px] text-[var(--color-text-3)] italic border-t border-[var(--color-base-4)] pt-2">
            These are engine-generated suggestions, not certified operational instructions.
            Always follow your organisation's approved maintenance procedures.
          </p>
        </div>
      </InsightSection>

    </div>
  );
}
